version: '3'

services:

  minio:
    image: minio/minio:RELEASE.2019-10-12T01-39-57Z
    restart: always
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    volumes:
      - ${DATADIR}/minio/data:/data
      - ${DATADIR}/minio/config:/root/.minio
    command: server /data
